-- ============================================
-- Inventory Dashboard — Database Schema
-- Run this SQL in Supabase SQL Editor
-- ============================================

-- Create the products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  stock_count INT NOT NULL DEFAULT 0,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Seed initial data
INSERT INTO products (name, stock_count)
VALUES
  ('T-Shirt - Small', 50),
  ('Jeans - Blue', 25),
  ('Sneakers - Black', 12);

-- (Optional) Enable Row Level Security and allow public read access
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON products
  FOR SELECT
  USING (true);

-- Enable Realtime for the products table
ALTER PUBLICATION supabase_realtime ADD TABLE products;